# ============================================================================
# LIST ALL BUSINESSES
# ============================================================================

query ListAllBusinesses @auth(level: PUBLIC) {
  businesses {
    id
    name
    tier
    subscriptionStartDate
    subscriptionEndDate
    isActive
    maxUsers
    maxLocations
    logo
    banner
    phone
    createdAt
    updatedAt
  }
}
