// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform, kReleaseMode;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...\n/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static const String environment = String.fromEnvironment(
    'ENVIRONMENT',
    defaultValue: 'development',
  );

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // Domain-based detection to ensure Production is used on the live site
      // even if the build flag was missed.
      final host = Uri.base.host;
      if (host == 'bizpharma.app' || host == 'www.bizpharma.app') {
        return webProd;
      }

      switch (environment) {
        case 'production':
          return webProd;
        case 'staging':
          return webStaging;
        default:
          return webDev;
      }
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions webDev = FirebaseOptions(
    apiKey: 'AIzaSyD1EIbEbBVBs5PqqgRkuZ185a78NfzWng0',
    appId: '1:381385750800:web:YOUR_WEB_APP_ID',
    messagingSenderId: '381385750800',
    projectId: 'bizpharma-4e73a',
    authDomain: 'bizpharma-4e73a.firebaseapp.com',
    storageBucket: 'bizpharma-4e73a.firebasestorage.app',
  );

  static const FirebaseOptions webStaging = FirebaseOptions(
    apiKey: 'AIzaSyArbFbooj4xmHeMhXwtrA3Ch5qTrsivgJM',
    authDomain: 'bizpharma-staging.firebaseapp.com',
    projectId: 'bizpharma-staging',
    storageBucket: 'bizpharma-staging.firebasestorage.app',
    messagingSenderId: '329922858118',
    appId: '1:329922858118:web:80322052214a378573d507',
  );

  static const FirebaseOptions webProd = FirebaseOptions(
    apiKey: 'AIzaSyARNecjdxHUCvcQOadO6hiAaIGExsrnSbs',
    authDomain: 'bizpharma-prod.firebaseapp.com',
    projectId: 'bizpharma-prod',
    storageBucket: 'bizpharma-prod.firebasestorage.app',
    messagingSenderId: '359227923382',
    appId: '1:359227923382:web:6ff76b79629b6f2b3eff17',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1EIbEbBVBs5PqqgRkuZ185a78NfzWng0',
    appId: '1:381385750800:android:7e989e9d9b77407fe44d95',
    messagingSenderId: '381385750800',
    projectId: 'bizpharma-4e73a',
    storageBucket: 'bizpharma-4e73a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl3VQJ61yoPQ1faYp95jxvP-CpvV5DwY0',
    appId: '1:381385750800:ios:f55b0dacd5671359e44d95',
    messagingSenderId: '381385750800',
    projectId: 'bizpharma-4e73a',
    storageBucket: 'bizpharma-4e73a.firebasestorage.app',
    iosBundleId: 'app.bizpharma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl3VQJ61yoPQ1faYp95jxvP-CpvV5DwY0',
    appId: '1:381385750800:ios:f55b0dacd5671359e44d95',
    messagingSenderId: '381385750800',
    projectId: 'bizpharma-4e73a',
    storageBucket: 'bizpharma-4e73a.firebasestorage.app',
    iosBundleId: 'app.bizpharma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1EIbEbBVBs5PqqgRkuZ185a78NfzWng0',
    appId: '1:381385750800:web:YOUR_WEB_APP_ID',
    messagingSenderId: '381385750800',
    projectId: 'bizpharma-4e73a',
    authDomain: 'bizpharma-4e73a.firebaseapp.com',
    storageBucket: 'bizpharma-4e73a.firebasestorage.app',
  );
}
