// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...\n/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1EIbEbBVBs5PqqgRkuZ185a78NfzWng0',
    appId: '1:381385750800:web:YOUR_WEB_APP_ID',
    messagingSenderId: '381385750800',
    projectId: 'bizpharma-4e73a',
    authDomain: 'bizpharma-4e73a.firebaseapp.com',
    storageBucket: 'bizpharma-4e73a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1EIbEbBVBs5PqqgRkuZ185a78NfzWng0',
    appId: '1:381385750800:android:7e989e9d9b77407fe44d95',
    messagingSenderId: '381385750800',
    projectId: 'bizpharma-4e73a',
    storageBucket: 'bizpharma-4e73a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl3VQJ61yoPQ1faYp95jxvP-CpvV5DwY0',
    appId: '1:381385750800:ios:f55b0dacd5671359e44d95',
    messagingSenderId: '381385750800',
    projectId: 'bizpharma-4e73a',
    storageBucket: 'bizpharma-4e73a.firebasestorage.app',
    iosBundleId: 'app.bizpharma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl3VQJ61yoPQ1faYp95jxvP-CpvV5DwY0',
    appId: '1:381385750800:ios:f55b0dacd5671359e44d95',
    messagingSenderId: '381385750800',
    projectId: 'bizpharma-4e73a',
    storageBucket: 'bizpharma-4e73a.firebasestorage.app',
    iosBundleId: 'app.bizpharma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1EIbEbBVBs5PqqgRkuZ185a78NfzWng0',
    appId: '1:381385750800:web:YOUR_WEB_APP_ID',
    messagingSenderId: '381385750800',
    projectId: 'bizpharma-4e73a',
    authDomain: 'bizpharma-4e73a.firebaseapp.com',
    storageBucket: 'bizpharma-4e73a.firebasestorage.app',
  );
}
