query VerifyProduct @auth(level: USER) {
  products(where: { genericName: { eq: "Paracetamol" } }) {
    id
    genericName
    brandName
    internalSKU
    manufacturer {
      name
    }
    business {
      name
    }
    category {
      name
    }
    isActive
  }
}
