
# This is a file for you to write an un-named query.
# Only one un-named query is allowed per file.
query {
  businesss{
    name
    subscriptionStartDate
    subscriptionEndDate
    isActive
    maxUsers
    maxLocations
    logo
    banner
    phone
    createdAt
    updatedAt
  }
}